### ISSUE TITLE
Kserve not installing for arm64 builds

### ISSUE THREAD

**Issue by saumil-d** [modzy/chassis#93] opened 2022-04-01 00:13 UTC
KServe fails to install during arm64 builds due to conflicting dependency issues

**Comment by bsepaul** [comment] 2022-07-19 15:09
I think I may be running into an issue related to this. I [manually deployed the chassis service](https://chassis.ml/getting-started/deploy-manual/) and am using minikube to run the service. I also have kubectl and kserve installed on my machine. 

I am following the [tutorial to build a model](https://chassis.ml/tutorials/ds-connect/). I can run the test_env() just fine and everything works up until actually publishing the image. When I run the chassis builder job using chassis_model.publish(), the final_status returns the following error message towards the end:

```
ERROR: Cannot install -r requirements.txt (line 3) because these package versions have conflicting dependencies.

The conflict is caused by:
    kserve 0.8.0.1 depends on ray[serve]==1.9.0
    kserve 0.8.0 depends on ray[serve]==1.9.0
    kserve 0.7.0 depends on ray[serve]==1.5.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
I'm not sure if this is related to the issue being opened, but I thought since there were dependency issues it could be.
I have the Apple M1 Pro Chip and am on macOS Monterey 12.4

**Comment by bmunday3** [comment] 2023-10-18 16:14
This was primarily caused by the MLflow dependency. This was removed entirely as a dependency in v1.5 and successfully tested, so this issue is fixed now as well.

**Closed by bmunday3** 2023-10-18 16:14 UTC
